{% set name = "pybloom_live" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99545c5d3b05bd388b5491e36b823b706830a686ba18b4c19063d08de5321110

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bitarray >=0.3.4

test:
  imports:
    - pybloom_live

about:
  home: https://github.com/joseph-fox/python-bloomfilter
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Scalable Bloom Filter implemented in Python

extra:
  recipe-maintainers:
    - roll
