travis:
  secure:
    BINSTAR_TOKEN: CrpPHv2X1TkrrAZrWhHolA+FHtOZre0SIVJC+5jmbNiu4Yb+yOcTkMIEGFroR+Ti77dw0o0AUm7SUf9G634shStGDLvlEB5f+9o03TRNH9Bc63OKDno5A2tXh2BbkFhlOPcPj11Ual3UYQoJPTbPTRM4qOfc+VwuJMfuLCDdQ/cHNOhTssdvk+O33PjO6LXsm97P7HeIyFIYvyQ6MKp5Ec7KF6liJiteAYMxLKnxB9meR3YCLnE2GbeIxK4BJ9RQd8qQU7g+DNG6zrINz0Mr5Y0uev1CeZjZ96pAMx7uO442yUMeLWYTclTiTlXfPLF4+4HvF02JCTOQK1CQFAnIKFyQlInR4flGH6Y46SwCWLOnWmKrCYOPAZwDo/QK+ARXCa8H2ZRs3wmKlyAWKUdC6xvDqDO1qSlbuNdy1JT5PPPs52IuqZZ19hDo8PiKmFog3OLUMSNISLAFM/sNNalrvTQVRod8Jj288hjulU++42Thd1Jrl3+sQXRzofJoZ74P+FCCi2YzlsmAwr1QRWcuHJ8JsOliIms/TWPU74Tih99E+o+n070x1/9046bXOwhM6VfXPD5tXH8d1aq8VbbcaEZ06hbqSZ+ZJLYVlCj7dyrV/f12dOsyzW9Eg934Ria2IkCd/qp20rOQigS2cscKrr92TdGf/Ma+IrusGVt7MzU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
